services:
  postgres:
    image: postgres:16.3
    container_name: user_postgres_db
    command:
      - postgres
      - -c
      - log_statement=all
      - -c
      - max_connections=500
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: juan
      POSTGRES_PASSWORD: juan_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../../../database/migrations/V1__users_table.sql:/docker-entrypoint-initdb.d/V1__users_table.sql
# TODO: use flyway properly for the migrations
    healthcheck:
      test: pg_isready -U juan -d user_db
      start_period: 0s
      interval: 1s
      timeout: 500ms
      retries: 10
